# flake8: noqa

"""
    Bundesrat: Live Informationen

    Bundesrat Informationen API   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from deutschland.bundesrat.api_client import ApiClient

# import Configuration
from deutschland.bundesrat.configuration import Configuration

# import exceptions
from deutschland.bundesrat.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)
