"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zoll
from zoll.model.exchange_rates_kurse import ExchangeRatesKurse
globals()['ExchangeRatesKurse'] = ExchangeRatesKurse
from zoll.model.exchange_rates import ExchangeRates


class TestExchangeRates(unittest.TestCase):
    """ExchangeRates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExchangeRates(self):
        """Test ExchangeRates"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExchangeRates()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
