"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zoll
from zoll.model.country import Country
globals()['Country'] = Country
from zoll.model.countries_data import CountriesData


class TestCountriesData(unittest.TestCase):
    """CountriesData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountriesData(self):
        """Test CountriesData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CountriesData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
