"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import zoll
from zoll.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_kategorien_get(self):
        """Test case for kategorien_get

        Produktkategorien  # noqa: E501
        """
        pass

    def test_kurse_app_kurs_export_txt_get(self):
        """Test case for kurse_app_kurs_export_txt_get

        Währungskurse  # noqa: E501
        """
        pass

    def test_laender_get(self):
        """Test case for laender_get

        """
        pass

    def test_produkte_get(self):
        """Test case for produkte_get

        Produkte  # noqa: E501
        """
        pass

    def test_produkteinheiten_get(self):
        """Test case for produkteinheiten_get

        """
        pass

    def test_produktgruppen_get(self):
        """Test case for produktgruppen_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
