"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zoll
from zoll.model.exchange_rates_kurse import ExchangeRatesKurse


class TestExchangeRatesKurse(unittest.TestCase):
    """ExchangeRatesKurse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExchangeRatesKurse(self):
        """Test ExchangeRatesKurse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExchangeRatesKurse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
