"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zoll
from zoll.model.product_groups_data import ProductGroupsData
globals()['ProductGroupsData'] = ProductGroupsData
from zoll.model.product_groups import ProductGroups


class TestProductGroups(unittest.TestCase):
    """ProductGroups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductGroups(self):
        """Test ProductGroups"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProductGroups()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
