"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import zoll
from zoll.model.categories_data import CategoriesData
globals()['CategoriesData'] = CategoriesData
from zoll.model.categories import Categories


class TestCategories(unittest.TestCase):
    """Categories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategories(self):
        """Test Categories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Categories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
