# flake8: noqa

"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from deutschland.interpol.api_client import ApiClient

# import Configuration
from deutschland.interpol.configuration import Configuration

# import exceptions
from deutschland.interpol.exceptions import OpenApiException
from deutschland.interpol.exceptions import ApiAttributeError
from deutschland.interpol.exceptions import ApiTypeError
from deutschland.interpol.exceptions import ApiValueError
from deutschland.interpol.exceptions import ApiKeyError
from deutschland.interpol.exceptions import ApiException
