# flake8: noqa

"""
    Bundesagentur für Arbeit: Jobsuche API

    Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br> Die Authentifizierung funktioniert per OAuth 2 Client Credentials mit JWTs. Folgende Client-Credentials können dafür verwendet werden:<br><br> **ClientID:** c003a37f-024f-462a-b36d-b001be4cd24a <br> **ClientSecret:** 32a39620-32b3-4307-9aa1-511e3d7f48a8  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from deutschland.jobsuche.api_client import ApiClient

# import Configuration
from deutschland.jobsuche.configuration import Configuration

# import exceptions
from deutschland.jobsuche.exceptions import OpenApiException
from deutschland.jobsuche.exceptions import ApiAttributeError
from deutschland.jobsuche.exceptions import ApiTypeError
from deutschland.jobsuche.exceptions import ApiValueError
from deutschland.jobsuche.exceptions import ApiKeyError
from deutschland.jobsuche.exceptions import ApiException
