"""
    Bundesagentur für Arbeit: Jobsuche API

    Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br> Die Authentifizierung funktioniert per OAuth 2 Client Credentials mit JWTs. Folgende Client-Credentials können dafür verwendet werden:<br><br> **ClientID:** c003a37f-024f-462a-b36d-b001be4cd24a <br> **ClientSecret:** 32a39620-32b3-4307-9aa1-511e3d7f48a8  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import jobsuche
from jobsuche.model.job_application_details_angebotskontakt import JobApplicationDetailsAngebotskontakt
globals()['JobApplicationDetailsAngebotskontakt'] = JobApplicationDetailsAngebotskontakt
from jobsuche.model.job_application_details import JobApplicationDetails


class TestJobApplicationDetails(unittest.TestCase):
    """JobApplicationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobApplicationDetails(self):
        """Test JobApplicationDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobApplicationDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
