"""
    Bundesagentur für Arbeit: Jobsuche API

    Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br> Die Authentifizierung funktioniert per OAuth 2 Client Credentials mit JWTs. Folgende Client-Credentials können dafür verwendet werden:<br><br> **ClientID:** c003a37f-024f-462a-b36d-b001be4cd24a <br> **ClientSecret:** 32a39620-32b3-4307-9aa1-511e3d7f48a8  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import jobsuche
from jobsuche.model.job_search_response_aggregierungen_bundesland import JobSearchResponseAggregierungenBundesland
from jobsuche.model.job_search_response_aggregierungen_plzebene2 import JobSearchResponseAggregierungenPlzebene2
globals()['JobSearchResponseAggregierungenBundesland'] = JobSearchResponseAggregierungenBundesland
globals()['JobSearchResponseAggregierungenPlzebene2'] = JobSearchResponseAggregierungenPlzebene2
from jobsuche.model.job_search_response_aggregierungen import JobSearchResponseAggregierungen


class TestJobSearchResponseAggregierungen(unittest.TestCase):
    """JobSearchResponseAggregierungen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobSearchResponseAggregierungen(self):
        """Test JobSearchResponseAggregierungen"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobSearchResponseAggregierungen()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
