"""
    Bundesagentur für Arbeit: Jobsuche API

    Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br> Die Authentifizierung funktioniert per OAuth 2 Client Credentials mit JWTs. Folgende Client-Credentials können dafür verwendet werden:<br><br> **ClientID:** c003a37f-024f-462a-b36d-b001be4cd24a <br> **ClientSecret:** 32a39620-32b3-4307-9aa1-511e3d7f48a8  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import jobsuche
from jobsuche.model.job_details_arbeitgeber_adresse import JobDetailsArbeitgeberAdresse
from jobsuche.model.job_details_arbeitsorte import JobDetailsArbeitsorte
from jobsuche.model.job_details_ausbildungen import JobDetailsAusbildungen
from jobsuche.model.job_details_fertigkeiten import JobDetailsFertigkeiten
from jobsuche.model.job_details_fuehrungskompetenzen import JobDetailsFuehrungskompetenzen
from jobsuche.model.job_details_links import JobDetailsLinks
from jobsuche.model.job_details_mobilitaet import JobDetailsMobilitaet
from jobsuche.model.job_details_sprachkenntnisse import JobDetailsSprachkenntnisse
globals()['JobDetailsArbeitgeberAdresse'] = JobDetailsArbeitgeberAdresse
globals()['JobDetailsArbeitsorte'] = JobDetailsArbeitsorte
globals()['JobDetailsAusbildungen'] = JobDetailsAusbildungen
globals()['JobDetailsFertigkeiten'] = JobDetailsFertigkeiten
globals()['JobDetailsFuehrungskompetenzen'] = JobDetailsFuehrungskompetenzen
globals()['JobDetailsLinks'] = JobDetailsLinks
globals()['JobDetailsMobilitaet'] = JobDetailsMobilitaet
globals()['JobDetailsSprachkenntnisse'] = JobDetailsSprachkenntnisse
from jobsuche.model.job_details import JobDetails


class TestJobDetails(unittest.TestCase):
    """JobDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobDetails(self):
        """Test JobDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
