def test_all_imports():
    from deutschland.autobahn.apis import DefaultApi
    from deutschland.bundesanzeiger import Bundesanzeiger
    from deutschland.bundesnetzagentur import Rufzeichen
    from deutschland.bundesrat.apis import DefaultApi
    from deutschland.bundestag.apis import DefaultApi
    from deutschland.bundeswahlleiter import Bundeswahlleiter
    from deutschland.destatis.apis import DefaultApi
    from deutschland.dwd.apis import DefaultApi
    from deutschland.handelsregister import Handelsregister
    from deutschland.handelsregister.registrations import Registrations
    from deutschland.interpol.apis import DefaultApi
    from deutschland.jobsuche.apis import DefaultApi
    from deutschland.ladestationen.apis import DefaultApi
    from deutschland.lebensmittelwarnung.apis import DefaultApi
    from deutschland.mudab.apis import DefaultApi
    from deutschland.nina.apis import DefaultApi
    from deutschland.polizei_brandenburg.apis import DefaultApi
    from deutschland.presseportal import PresseportalApi
    from deutschland.risikogebiete.apis import DefaultApi
    from deutschland.smard.apis import DefaultApi
    from deutschland.strahlenschutz.apis import DefaultApi
    from deutschland.travelwarning.apis import DefaultApi
    from deutschland.verena import Verena
    from deutschland.zoll.apis import DefaultApi
    from deutschland.pegel_online.apis import WaterApi
    from deutschland.bundestag_lobbyregister.apis import DefaultApi
