# flake8: noqa

"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from deutschland.nina.api_client import ApiClient

# import Configuration
from deutschland.nina.configuration import Configuration

# import exceptions
from deutschland.nina.exceptions import OpenApiException
from deutschland.nina.exceptions import ApiAttributeError
from deutschland.nina.exceptions import ApiTypeError
from deutschland.nina.exceptions import ApiValueError
from deutschland.nina.exceptions import ApiKeyError
from deutschland.nina.exceptions import ApiException
