"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import nina
from nina.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_appdata_covid_covidrules_deags_json_get(self):
        """Test case for appdata_covid_covidrules_deags_json_get

        Corona Regelungen nach AGS  # noqa: E501
        """
        pass

    def test_biwapp_map_data_json_get(self):
        """Test case for biwapp_map_data_json_get

        Biwapp Meldungen  # noqa: E501
        """
        pass

    def test_dashboard_ags_json_get(self):
        """Test case for dashboard_ags_json_get

        Meldungsübersicht nach AGS  # noqa: E501
        """
        pass

    def test_katwarn_map_data_json_get(self):
        """Test case for katwarn_map_data_json_get

        Katwarn Meldungen  # noqa: E501
        """
        pass

    def test_mowas_map_data_json_get(self):
        """Test case for mowas_map_data_json_get

        Mowas Meldungen  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
