"""
    Bundesamt für Bevölkerungsschutz: NINA API

    Erhalten Sie wichtige Warnmeldungen des Bevölkerungsschutzes für Gefahrenlagen wie zum Beispiel Gefahrstoffausbreitung oder Unwetter per Programmierschnittstelle.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nina
from nina.model.ags_covid_rules_regulations_sections_land_icon import AGSCovidRulesRegulationsSectionsLANDIcon
globals()['AGSCovidRulesRegulationsSectionsLANDIcon'] = AGSCovidRulesRegulationsSectionsLANDIcon
from nina.model.ags_covid_rules_regulations_sections_land import AGSCovidRulesRegulationsSectionsLAND


class TestAGSCovidRulesRegulationsSectionsLAND(unittest.TestCase):
    """AGSCovidRulesRegulationsSectionsLAND unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAGSCovidRulesRegulationsSectionsLAND(self):
        """Test AGSCovidRulesRegulationsSectionsLAND"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AGSCovidRulesRegulationsSectionsLAND()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
