"""
    Polizei Brandenburg: App

    Polizei Brandenburg Nachrichten, Hochwasser-, Verkehrs- und Waldbrandwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import polizei-brandenburg
from polizei-brandenburg.model.verkehr_data import VerkehrData
globals()['VerkehrData'] = VerkehrData
from polizei-brandenburg.model.verkehr import Verkehr


class TestVerkehr(unittest.TestCase):
    """Verkehr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerkehr(self):
        """Test Verkehr"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Verkehr()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
