"""
    Bundesnetzagentur: Ladesäulenregister

    API des Ladesäulenregisters der Bundesnetzagentur  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ladestationen
from ladestationen.model.station_overview_features import StationOverviewFeatures
from ladestationen.model.station_overview_fields import StationOverviewFields
from ladestationen.model.station_overview_spatial_reference import StationOverviewSpatialReference
from ladestationen.model.station_overview_transform import StationOverviewTransform
from ladestationen.model.station_overview_unique_id_field import StationOverviewUniqueIdField
globals()['StationOverviewFeatures'] = StationOverviewFeatures
globals()['StationOverviewFields'] = StationOverviewFields
globals()['StationOverviewSpatialReference'] = StationOverviewSpatialReference
globals()['StationOverviewTransform'] = StationOverviewTransform
globals()['StationOverviewUniqueIdField'] = StationOverviewUniqueIdField
from ladestationen.model.station_overview import StationOverview


class TestStationOverview(unittest.TestCase):
    """StationOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStationOverview(self):
        """Test StationOverview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StationOverview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
