"""
    Bundesnetzagentur: Ladesäulenregister

    API des Ladesäulenregisters der Bundesnetzagentur  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ladestationen
from ladestationen.model.station_overview_spatial_reference import StationOverviewSpatialReference
globals()['StationOverviewSpatialReference'] = StationOverviewSpatialReference
from ladestationen.model.geometry import Geometry


class TestGeometry(unittest.TestCase):
    """Geometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeometry(self):
        """Test Geometry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Geometry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
