"""
    Bundesnetzagentur: Ladesäulenregister

    API des Ladesäulenregisters der Bundesnetzagentur  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ladestationen
from ladestationen.model.station_overview_spatial_reference import StationOverviewSpatialReference


class TestStationOverviewSpatialReference(unittest.TestCase):
    """StationOverviewSpatialReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStationOverviewSpatialReference(self):
        """Test StationOverviewSpatialReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StationOverviewSpatialReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
