"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import interpol
from interpol.model.red_notice_detail_arrest_warrants import RedNoticeDetailArrestWarrants


class TestRedNoticeDetailArrestWarrants(unittest.TestCase):
    """RedNoticeDetailArrestWarrants unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailArrestWarrants(self):
        """Test RedNoticeDetailArrestWarrants"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailArrestWarrants()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
