"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import interpol
from interpol.model.red_notices_links_self import RedNoticesLinksSelf


class TestRedNoticesLinksSelf(unittest.TestCase):
    """RedNoticesLinksSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticesLinksSelf(self):
        """Test RedNoticesLinksSelf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticesLinksSelf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
