"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import interpol
from interpol.model.red_notice_detail_images_embedded_links import RedNoticeDetailImagesEmbeddedLinks
globals()['RedNoticeDetailImagesEmbeddedLinks'] = RedNoticeDetailImagesEmbeddedLinks
from interpol.model.red_notice_detail_images_embedded_images import RedNoticeDetailImagesEmbeddedImages


class TestRedNoticeDetailImagesEmbeddedImages(unittest.TestCase):
    """RedNoticeDetailImagesEmbeddedImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailImagesEmbeddedImages(self):
        """Test RedNoticeDetailImagesEmbeddedImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailImagesEmbeddedImages()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
