# flake8: noqa

"""
    Auswärtiges Amt OpenData Schnittstelle

    Dies ist die Beschreibung für die Schnittstelle zum Zugriff auf die Daten des Auswärtigen Amtes im Rahmen der OpenData Initiative.  Deaktivierung Die Schnittstelle kann deaktiviert werden, in dem Fall wird ein leeres JSON zurückgegeben.  Fehlerfall:  Im Fehlerfall wird ein leeres JSON Objekt zurückgegeben.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from travelwarning.api_client import ApiClient

# import Configuration
from travelwarning.configuration import Configuration

# import exceptions
from travelwarning.exceptions import OpenApiException
from travelwarning.exceptions import ApiAttributeError
from travelwarning.exceptions import ApiTypeError
from travelwarning.exceptions import ApiValueError
from travelwarning.exceptions import ApiKeyError
from travelwarning.exceptions import ApiException
