"""
    Robert Koch Institut: Corona Risikogebiete API

    Aktuelle Corona Risikogebietsinformationen als API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import risikogebiete
from risikogebiete.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_risikogebiete_get(self):
        """Test case for risikogebiete_get

        Liste der Länder  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
