"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mudab
from mudab.model.filter_action import FilterAction
globals()['FilterAction'] = FilterAction
from mudab.model.filter import Filter


class TestFilter(unittest.TestCase):
    """Filter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilter(self):
        """Test Filter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Filter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
