"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mudab
from mudab.model.range import Range


class TestRange(unittest.TestCase):
    """Range unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRange(self):
        """Test Range"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Range()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
