"""
    Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

    Meeres-Monitoringdaten von Küstenbundesländern und Forschungseinrichtungen   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import mudab
from mudab.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_mess_stationen(self):
        """Test case for list_mess_stationen

        Liste aller Messstationen  # noqa: E501
        """
        pass

    def test_list_parameter(self):
        """Test case for list_parameter

        Liste aller Parameter  # noqa: E501
        """
        pass

    def test_list_parameter_values(self):
        """Test case for list_parameter_values

        Liste aller Messwerte  # noqa: E501
        """
        pass

    def test_list_parameters_biologie(self):
        """Test case for list_parameters_biologie

        Liste aller Parameter im Biologie Kompartiment  # noqa: E501
        """
        pass

    def test_list_parameters_biota(self):
        """Test case for list_parameters_biota

        Liste aller Parameter im Biota Kompartiment  # noqa: E501
        """
        pass

    def test_list_parameters_sediment(self):
        """Test case for list_parameters_sediment

        Liste aller Parameter im Sediment Kompartiment  # noqa: E501
        """
        pass

    def test_list_parameters_wasser(self):
        """Test case for list_parameters_wasser

        Liste aller Parameter im Wasser Kompartiment  # noqa: E501
        """
        pass

    def test_list_plc_stations(self):
        """Test case for list_plc_stations

        Liste aller HELCOM PLC Stationen  # noqa: E501
        """
        pass

    def test_list_projekt_stationen(self):
        """Test case for list_projekt_stationen

        Liste aller Projekt Stationen  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
