# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from jobsuche.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from jobsuche.model.job_application_details import JobApplicationDetails
from jobsuche.model.job_application_details_angebotskontakt import JobApplicationDetailsAngebotskontakt
from jobsuche.model.job_application_details_angebotskontakt_festnetznummer import JobApplicationDetailsAngebotskontaktFestnetznummer
from jobsuche.model.job_application_details_angebotskontakt_mobilnummer import JobApplicationDetailsAngebotskontaktMobilnummer
from jobsuche.model.job_details import JobDetails
from jobsuche.model.job_details_arbeitgeber_adresse import JobDetailsArbeitgeberAdresse
from jobsuche.model.job_details_arbeitsorte import JobDetailsArbeitsorte
from jobsuche.model.job_details_ausbildungen import JobDetailsAusbildungen
from jobsuche.model.job_details_fertigkeiten import JobDetailsFertigkeiten
from jobsuche.model.job_details_fuehrungskompetenzen import JobDetailsFuehrungskompetenzen
from jobsuche.model.job_details_koordinaten import JobDetailsKoordinaten
from jobsuche.model.job_details_links import JobDetailsLinks
from jobsuche.model.job_details_links_arbeitgeberlogo import JobDetailsLinksArbeitgeberlogo
from jobsuche.model.job_details_links_bewerbung import JobDetailsLinksBewerbung
from jobsuche.model.job_details_links_details import JobDetailsLinksDetails
from jobsuche.model.job_details_links_self import JobDetailsLinksSelf
from jobsuche.model.job_details_mobilitaet import JobDetailsMobilitaet
from jobsuche.model.job_details_sprachkenntnisse import JobDetailsSprachkenntnisse
from jobsuche.model.job_search_response import JobSearchResponse
from jobsuche.model.job_search_response_aggregierungen import JobSearchResponseAggregierungen
from jobsuche.model.job_search_response_aggregierungen_bundesland import JobSearchResponseAggregierungenBundesland
from jobsuche.model.job_search_response_aggregierungen_plzebene2 import JobSearchResponseAggregierungenPlzebene2
from jobsuche.model.job_search_response_auswahl import JobSearchResponseAuswahl
from jobsuche.model.job_search_response_embedded import JobSearchResponseEmbedded
from jobsuche.model.job_search_response_embedded_arbeitsort import JobSearchResponseEmbeddedArbeitsort
from jobsuche.model.job_search_response_embedded_arbeitsort_koordinaten import JobSearchResponseEmbeddedArbeitsortKoordinaten
from jobsuche.model.job_search_response_embedded_jobs import JobSearchResponseEmbeddedJobs
from jobsuche.model.job_search_response_embedded_links import JobSearchResponseEmbeddedLinks
from jobsuche.model.job_search_response_embedded_links_arbeitgeberlogo import JobSearchResponseEmbeddedLinksArbeitgeberlogo
from jobsuche.model.job_search_response_embedded_links_details import JobSearchResponseEmbeddedLinksDetails
from jobsuche.model.job_search_response_embedded_links_jobdetails import JobSearchResponseEmbeddedLinksJobdetails
from jobsuche.model.job_search_response_facetten import JobSearchResponseFacetten
from jobsuche.model.job_search_response_links import JobSearchResponseLinks
from jobsuche.model.job_search_response_links_first import JobSearchResponseLinksFirst
from jobsuche.model.job_search_response_links_last import JobSearchResponseLinksLast
from jobsuche.model.job_search_response_links_next import JobSearchResponseLinksNext
from jobsuche.model.job_search_response_links_self import JobSearchResponseLinksSelf
from jobsuche.model.job_search_response_page import JobSearchResponsePage
from jobsuche.model.job_search_response_parser_result import JobSearchResponseParserResult
from jobsuche.model.job_search_response_parser_result_koordinaten import JobSearchResponseParserResultKoordinaten
