"""
    Bundestag: Live Informationen

    Bundestag Informationen API   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from deutschland.bundestag.api_client import ApiClient, Endpoint as _Endpoint
from deutschland.bundestag.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types,
)


class DefaultApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.blueprint_servlet_content_articleidas_app_v2_newsarticle_xml_get_endpoint = _Endpoint(
            settings={
                "response_type": (str,),
                "auth": [],
                "endpoint_path": "/blueprint/servlet/content/{ARTICLE_ID}/asAppV2NewsarticleXml",
                "operation_id": "blueprint_servlet_content_articleidas_app_v2_newsarticle_xml_get",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [
                    "article_id",
                ],
                "required": [
                    "article_id",
                ],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "article_id": (int,),
                },
                "attribute_map": {
                    "article_id": "ARTICLE_ID",
                },
                "location_map": {
                    "article_id": "path",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/xml"],
                "content_type": [],
            },
            api_client=api_client,
        )
        self.iptv_player_macros_xs144277506_bttv_mobile_feed_vod_xml_get_endpoint = _Endpoint(
            settings={
                "response_type": (str,),
                "auth": [],
                "endpoint_path": "/iptv/player/macros/_x_s-144277506/bttv/mobile/feed_vod.xml",
                "operation_id": "iptv_player_macros_xs144277506_bttv_mobile_feed_vod_xml_get",
                "http_method": "GET",
                "servers": [
                    {
                        "url": "http://webtv.bundestag.de",
                        "description": "No description provided",
                    },
                ],
            },
            params_map={
                "all": [
                    "content_id",
                ],
                "required": [
                    "content_id",
                ],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "content_id": (int,),
                },
                "attribute_map": {
                    "content_id": "contentId",
                },
                "location_map": {
                    "content_id": "query",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/xml"],
                "content_type": [],
            },
            api_client=api_client,
        )
        self.static_appdata_plenum_v2_conferences_xml_get_endpoint = _Endpoint(
            settings={
                "response_type": (str,),
                "auth": [],
                "endpoint_path": "/static/appdata/plenum/v2/conferences.xml",
                "operation_id": "static_appdata_plenum_v2_conferences_xml_get",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [],
                "required": [],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {},
                "attribute_map": {},
                "location_map": {},
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/xml"],
                "content_type": [],
            },
            api_client=api_client,
        )
        self.static_appdata_plenum_v2_speaker_xml_get_endpoint = _Endpoint(
            settings={
                "response_type": (str,),
                "auth": [],
                "endpoint_path": "/static/appdata/plenum/v2/speaker.xml",
                "operation_id": "static_appdata_plenum_v2_speaker_xml_get",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [],
                "required": [],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {},
                "attribute_map": {},
                "location_map": {},
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/xml"],
                "content_type": [],
            },
            api_client=api_client,
        )
        self.xml_v2_ausschuesse_ausschussid_xml_get_endpoint = _Endpoint(
            settings={
                "response_type": (str,),
                "auth": [],
                "endpoint_path": "/xml/v2/ausschuesse/{AUSSCHUSS_ID}.xml",
                "operation_id": "xml_v2_ausschuesse_ausschussid_xml_get",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [
                    "ausschuss_id",
                ],
                "required": [
                    "ausschuss_id",
                ],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "ausschuss_id": (str,),
                },
                "attribute_map": {
                    "ausschuss_id": "AUSSCHUSS_ID",
                },
                "location_map": {
                    "ausschuss_id": "path",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/xml"],
                "content_type": [],
            },
            api_client=api_client,
        )
        self.xml_v2_ausschuesse_index_xml_get_endpoint = _Endpoint(
            settings={
                "response_type": (str,),
                "auth": [],
                "endpoint_path": "/xml/v2/ausschuesse/index.xml",
                "operation_id": "xml_v2_ausschuesse_index_xml_get",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [],
                "required": [],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {},
                "attribute_map": {},
                "location_map": {},
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/xml"],
                "content_type": [],
            },
            api_client=api_client,
        )
        self.xml_v2_mdb_biografien_mdbid_xml_get_endpoint = _Endpoint(
            settings={
                "response_type": (str,),
                "auth": [],
                "endpoint_path": "/xml/v2/mdb/biografien/{MDB_ID}.xml",
                "operation_id": "xml_v2_mdb_biografien_mdbid_xml_get",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [
                    "mdb_id",
                ],
                "required": [
                    "mdb_id",
                ],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "mdb_id": (int,),
                },
                "attribute_map": {
                    "mdb_id": "MDB_ID",
                },
                "location_map": {
                    "mdb_id": "path",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/xml"],
                "content_type": [],
            },
            api_client=api_client,
        )
        self.xml_v2_mdb_index_xml_get_endpoint = _Endpoint(
            settings={
                "response_type": (str,),
                "auth": [],
                "endpoint_path": "/xml/v2/mdb/index.xml",
                "operation_id": "xml_v2_mdb_index_xml_get",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [],
                "required": [],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {},
                "attribute_map": {},
                "location_map": {},
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/xml"],
                "content_type": [],
            },
            api_client=api_client,
        )

    def blueprint_servlet_content_articleidas_app_v2_newsarticle_xml_get(
        self, article_id, **kwargs
    ):
        """Artikel Details  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.blueprint_servlet_content_articleidas_app_v2_newsarticle_xml_get(article_id, async_req=True)
        >>> result = thread.get()

        Args:
            article_id (int): ID des Nachrichtenbeitrags

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            str
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_host_index"] = kwargs.get("_host_index")
        kwargs["article_id"] = article_id
        return self.blueprint_servlet_content_articleidas_app_v2_newsarticle_xml_get_endpoint.call_with_http_info(
            **kwargs
        )

    def iptv_player_macros_xs144277506_bttv_mobile_feed_vod_xml_get(
        self, content_id, **kwargs
    ):
        """Abruf eines Videos  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.iptv_player_macros_xs144277506_bttv_mobile_feed_vod_xml_get(content_id, async_req=True)
        >>> result = thread.get()

        Args:
            content_id (int): ID des MDB

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            str
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_host_index"] = kwargs.get("_host_index")
        kwargs["content_id"] = content_id
        return self.iptv_player_macros_xs144277506_bttv_mobile_feed_vod_xml_get_endpoint.call_with_http_info(
            **kwargs
        )

    def static_appdata_plenum_v2_conferences_xml_get(self, **kwargs):
        """Sitzungstag übersicht  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.static_appdata_plenum_v2_conferences_xml_get(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            str
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_host_index"] = kwargs.get("_host_index")
        return self.static_appdata_plenum_v2_conferences_xml_get_endpoint.call_with_http_info(
            **kwargs
        )

    def static_appdata_plenum_v2_speaker_xml_get(self, **kwargs):
        """Aktuelle Sprecher*in  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.static_appdata_plenum_v2_speaker_xml_get(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            str
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_host_index"] = kwargs.get("_host_index")
        return (
            self.static_appdata_plenum_v2_speaker_xml_get_endpoint.call_with_http_info(
                **kwargs
            )
        )

    def xml_v2_ausschuesse_ausschussid_xml_get(self, ausschuss_id, **kwargs):
        """Übersicht über die Ausschüsse  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.xml_v2_ausschuesse_ausschussid_xml_get(ausschuss_id, async_req=True)
        >>> result = thread.get()

        Args:
            ausschuss_id (str): ID des Ausschusses

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            str
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_host_index"] = kwargs.get("_host_index")
        kwargs["ausschuss_id"] = ausschuss_id
        return self.xml_v2_ausschuesse_ausschussid_xml_get_endpoint.call_with_http_info(
            **kwargs
        )

    def xml_v2_ausschuesse_index_xml_get(self, **kwargs):
        """Übersicht über die Ausschüsse  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.xml_v2_ausschuesse_index_xml_get(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            str
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_host_index"] = kwargs.get("_host_index")
        return self.xml_v2_ausschuesse_index_xml_get_endpoint.call_with_http_info(
            **kwargs
        )

    def xml_v2_mdb_biografien_mdbid_xml_get(self, mdb_id, **kwargs):
        """Abruf Details eines MDBS  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.xml_v2_mdb_biografien_mdbid_xml_get(mdb_id, async_req=True)
        >>> result = thread.get()

        Args:
            mdb_id (int): ID des MDB

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            str
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_host_index"] = kwargs.get("_host_index")
        kwargs["mdb_id"] = mdb_id
        return self.xml_v2_mdb_biografien_mdbid_xml_get_endpoint.call_with_http_info(
            **kwargs
        )

    def xml_v2_mdb_index_xml_get(self, **kwargs):
        """Übersicht über alle MDBS  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.xml_v2_mdb_index_xml_get(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            str
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_host_index"] = kwargs.get("_host_index")
        return self.xml_v2_mdb_index_xml_get_endpoint.call_with_http_info(**kwargs)
