"""
    Bundesrat: Live Informationen

    Bundesrat Informationen API   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import bundesrat
from bundesrat.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_i_os_shared_docs2_mitglieder_mitglieder_table_xml_get(self):
        """Test case for i_os_shared_docs2_mitglieder_mitglieder_table_xml_get

        Mitglieder  # noqa: E501
        """
        pass

    def test_i_os_shared_docs3_plenum_plenum_aktuelle_sitzung_table_xml_get(self):
        """Test case for i_os_shared_docs3_plenum_plenum_aktuelle_sitzung_table_xml_get

        Plenum aktuelle Sitzung  # noqa: E501
        """
        pass

    def test_i_os_shared_docs3_plenum_plenum_naechste_sitzungen_xml_get(self):
        """Test case for i_os_shared_docs3_plenum_plenum_naechste_sitzungen_xml_get

        Plenum nächste Sitzung  # noqa: E501
        """
        pass

    def test_i_os_shared_docs3_plenum_plenum_to_chronologisch_table_xml_get(self):
        """Test case for i_os_shared_docs3_plenum_plenum_to_chronologisch_table_xml_get

        Plenum Chronologisch  # noqa: E501
        """
        pass

    def test_i_osv301_aktuelles_aktuelles_table_xml_get(self):
        """Test case for i_osv301_aktuelles_aktuelles_table_xml_get

        Aktuelles  # noqa: E501
        """
        pass

    def test_i_osv302_termine_termine_table_xml_get(self):
        """Test case for i_osv302_termine_termine_table_xml_get

        Termine  # noqa: E501
        """
        pass

    def test_i_osv303_plenum_plenum_kompakt_table_xml_get(self):
        """Test case for i_osv303_plenum_plenum_kompakt_table_xml_get

        Plenum Kompakt  # noqa: E501
        """
        pass

    def test_i_osv305_bundesrat_praesidium_bundesrat_praesidium_xml_get(self):
        """Test case for i_osv305_bundesrat_praesidium_bundesrat_praesidium_xml_get

        Präsidium  # noqa: E501
        """
        pass

    def test_i_osv306_stimmen_stimmverteilung_xml_get(self):
        """Test case for i_osv306_stimmen_stimmverteilung_xml_get

        Stimmverteilung  # noqa: E501
        """
        pass

    def test_i_osv3_startlist_table_xml_get(self):
        """Test case for i_osv3_startlist_table_xml_get

        Übersicht API Endpunkte  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
