"""
    ODL-Info API

    Daten zur radioaktiven Belastung in Deutschland  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import strahlenschutz
from strahlenschutz.model.statistics_mwmax import StatisticsMwmax


class TestStatisticsMwmax(unittest.TestCase):
    """StatisticsMwmax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatisticsMwmax(self):
        """Test StatisticsMwmax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatisticsMwmax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
