"""
    ODL-Info API

    Daten zur radioaktiven Belastung in Deutschland  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import strahlenschutz
from strahlenschutz.model.station import Station


class TestStation(unittest.TestCase):
    """Station unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStation(self):
        """Test Station"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Station()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
