"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dwd
from dwd.model.warning_nowcast_warnings import WarningNowcastWarnings
globals()['WarningNowcastWarnings'] = WarningNowcastWarnings
from dwd.model.warning_nowcast import WarningNowcast


class TestWarningNowcast(unittest.TestCase):
    """WarningNowcast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWarningNowcast(self):
        """Test WarningNowcast"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WarningNowcast()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
