"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dwd
from dwd.model.gemeinde_warnings_binnen_see209901000 import GemeindeWarningsBinnenSee209901000


class TestGemeindeWarningsBinnenSee209901000(unittest.TestCase):
    """GemeindeWarningsBinnenSee209901000 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGemeindeWarningsBinnenSee209901000(self):
        """Test GemeindeWarningsBinnenSee209901000"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GemeindeWarningsBinnenSee209901000()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
