"""
    Deutscher Wetterdienst: API

    Aktuelle Wetterdaten von allen Deutschen Wetterstationen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dwd
from dwd.model.station_overview10865_days import StationOverview10865Days


class TestStationOverview10865Days(unittest.TestCase):
    """StationOverview10865Days unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStationOverview10865Days(self):
        """Test StationOverview10865Days"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StationOverview10865Days()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
